services:
  base:
    build:
      #ruta a trav√©s de la cual desde cualquier proyecto
      #se tiene aceeso a cualquier imagen (DFile), recurso
      context: /home/belen/devops/DespAW/Docker/Gaia
      dockerfile: ./dockerfiles/base/ubuntu/Dockerfile
      args:
        - USUARIO=${USUARIO}
    container_name: ctbaseDAW
    environment:
      - USUARIO="pepe"