services:
  web:
    build: #compilar la imagen a partir del Dockerfile
      context: .. #raiz del proyecto portfolio
      dockerfile: deploy/Dockerfile
    container_name: ctportfolioDAW
    ports:
      - "8820:80"